from __future__ import annotations

from pathlib import Path
from typing import Protocol

from app.application.dto import (
    CabeceraLote,
    DetallePaciente,
    FilaError,
    FilaPaciente,
    LineaBitacora,
    PreviewLote,
    ProgresoLote,
    ResultadoEjecucion,
    ResumenLote,
    SolicitudOperador,
)


class ILoginView(Protocol):
    def usuario(self) -> str: ...
    def contrasena(self) -> str: ...
    def mostrar_error(self, mensaje: str) -> None: ...
    def limpiar_error(self) -> None: ...
    def establecer_cargando(self, cargando: bool) -> None: ...


class IUploadView(Protocol):
    def establecer_cargando(self, mensaje: str | None) -> None: ...
    def mostrar_error(self, mensaje: str) -> None: ...
    def limpiar_error(self) -> None: ...


class IReviewView(Protocol):
    def mostrar_preview(self, preview: PreviewLote) -> None: ...


class IProcessingView(Protocol):
    def establecer_cabecera(self, cabecera: CabeceraLote) -> None: ...
    def establecer_filas(self, filas: tuple[FilaPaciente, ...]) -> None: ...
    def aplicar_actualizaciones(self, filas: tuple[FilaPaciente, ...]) -> None: ...
    def agregar_linea_bitacora(self, linea: LineaBitacora) -> None: ...
    def actualizar_progreso(self, progreso: ProgresoLote) -> None: ...
    def mostrar_solicitud_login_portal3(self, es_reproceso: bool = False) -> None: ...
    def ocultar_solicitud_login_portal3(self) -> None: ...
    def mostrar_solicitud_captcha(self, solicitud: SolicitudOperador) -> None: ...
    def ocultar_solicitud_captcha(self) -> None: ...
    def mostrar_lote_detenido(self, resultado: ResultadoEjecucion) -> None: ...
    def ocultar_lote_detenido(self) -> None: ...


class IPatientDetailView(Protocol):
    def mostrar_detalle(self, detalle: DetallePaciente) -> None: ...
    def limpiar(self) -> None: ...


class ISummaryView(Protocol):
    def mostrar_resumen(self, resumen: ResumenLote) -> None: ...


class IErrorsView(Protocol):
    def mostrar_errores(self, errores: tuple[FilaError, ...]) -> None: ...


class ISettingsView(Protocol):
    def mostrar_carpeta(self, carpeta: Path) -> None: ...
